version: 0.2.{build}

branches:
  only:
  - master
  
skip_non_tags: true

build:
  verbosity: minimal

cache:
  - packages -> **\packages.config 
  
platform: Any CPU
configuration: Release

artifacts:
  - path: bin\$(configuration)\*.nupkg
    name: NuGet
  - path: bin\$(configuration)\*.zip
    name: Zip


before_build:
  - nuget restore ConsoleWizard
  
nuget:
    disable_publish_on_pr: true
  
  
notifications:
- provider: Email
  to:
  - agolaszewski@agme.info
  subject: Inquirer.cs
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false