version: 0.2.{build}

environment:
  gitHub_authentication_token:
    secure: 8mNSYFdWNeQaYc9e+Ksm7uyuiEyA3LawxtNuAlHuS0pz8YwYO5SzqFzJByvPyXb/

branches:
  only:
  - master

build:
  verbosity: minimal

cache:
  - packages -> **\packages.config 
  
platform: Any CPU
configuration: Release

artifacts:
  - path: \*.nupkg
    name: NuGet
  - path: bin\$(configuration)
    name: Zip
    type: zip


before_build:
  - nuget restore ConsoleWizard

after_build:
  - nuget pack ConsoleWizard\ConsoleWizard.nuspec
  
nuget:
    disable_publish_on_pr: true
    
deploy:
    - provider: GitHub
      release: 'Release $(APPVEYOR_REPO_TAG_NAME) build $(APPVEYOR_BUILD_VERSION)'
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: ''
      prerelease: true
      artifact: Zip
      auth_token:
          secure: $(gitHub_authentication_token)
      on:
          branch: master
          appveyor_repo_tag_name: /v\d+\.\d+\.\d+/ 
          appveyor_repo_tag: true
  
  
notifications:
- provider: Email
  to:
  - agolaszewski@agme.info
  subject: Inquirer.cs
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false