version: '{build}'

branches:
  only:
  - master

build:
  verbosity: minimal

cache:
  - packages -> \Source\packages
  
platform: Any CPU
configuration: Release

artifacts:
  - path: \*.nupkg
    name: NuGet
  - path: \Source\Inquirer\bin\$(configuration)
    name: Inquirer
    type: zip


before_build:
  - nuget restore Source\Inquirer.sln

after_build:
  - nuget pack Inquirer.nuspec -Version 0.2.2-alpha
  
nuget:
    disable_publish_on_pr: true
    
deploy:
    - provider: GitHub
      release: 'Release $(APPVEYOR_REPO_TAG_NAME) build $(APPVEYOR_BUILD_VERSION)'
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: ''
      prerelease: true
      artifact: Inquirer
      auth_token:
          secure: JnUtQ9HEoqyYkHVkj5he8tbRauph96orT9i0eiyAB4R9a9g2hW4Mvm1SYDxsUvUg
      on:
          appveyor_repo_tag_name: /\d+\.\d+\.\d+/ 
          appveyor_repo_tag: true
          
    - provider: NuGet
      api_key:
          secure: jAS5nyIwacqXwMQl7CAi76q0+NAH3A3fGdvY8SCY+AfnNwSAooWfj4Bym6MPHdDF
      artifact: NuGet
      on:
          appveyor_repo_tag_name: /\d+\.\d+\.\d+/
          appveyor_repo_tag: true
  
  
notifications:
- provider: Email
  to:
  - agolaszewski@agme.info
  subject: Build {{status}}: {{projectName}} {{buildVersion}}
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false